version: '3'
services:
  #  The Laravel application
  app:
    container_name: hlb_app
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
    depends_on:
      - database

 # Web 1
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    depends_on:
      - app
  # Web replica
  web2:
    container_name: nginx_server2
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs_2/:/var/log/nginx
    depends_on:
      - app 
  # The Database
  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: backendHLB
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - 8993:3306

   # The Load balancer 
  load_balancer:
    container_name: load_balancer
    build: ./haproxy
    ports:
      - 8080:8080
    expose: 
      - 8080
    depends_on:
      - web 
      - web2 

volumes:
  dbdata: