version: '3'
services:

  #PHP Service
  hlb_app:
    build:
      context: .
      working_dir: /var/www
      volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - hlb_db
    environment:
      SERVICE_NAME: hlb-app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: root
      DB_PORT: 3306
    networks:
      - app_network

  #Nginx Service
  hlb_nginx:
    image: nginx:stable-alpine
    container_name: hlb_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  hlb_db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: backendHLB
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_PASSWORD:
      volumes:
        - ./database/content:/var/lib/mysql/
        - ./mysql/my.cnf:/etc/mysql/my.cnf
      networks:
        - app-network

#Docker Networks
networks:
  app_network:
    driver: bridge